# PRACTICA 8 REGRESIÓN LINEAL, MÚLTIPLE Y LOGÍSTICA

#### TAA - 10 MAYO
#### MIGUEL CHAVEINTE GARCÍA

In [1]:
import pandas as pd
import numpy as np
from sys import float_info
from sklearn.preprocessing import MinMaxScaler, LabelBinarizer
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as ac

#### Apartado 1

In [2]:
fichero_entreno = pd.read_csv("./avila-tr.txt", header= None)
print(fichero_entreno.shape)

fichero_test= pd.read_csv("./avila-ts.txt", header= None)
print(fichero_test.shape)

(10430, 11)
(10437, 11)


In [3]:
data = pd.concat([fichero_entreno,fichero_test])
# Añadimos cabecera para nombrar los atributos
data.columns = ['F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','Class']
data

F1        F2        F3        F4        F5        F6        F7  \
0      0.266074 -0.165620  0.320980  0.483299  0.172340  0.273364  0.371178   
1      0.130292  0.870736 -3.210528  0.062493  0.261718  1.436060  1.465940   
2     -0.116585  0.069915  0.068476 -0.783147  0.261718  0.439463 -0.081827   
3      0.031541  0.297600 -3.210528 -0.583590 -0.721442 -0.307984  0.710932   
4      0.229043  0.807926 -0.052442  0.082634  0.261718  0.148790  0.635431   
...         ...       ...       ...       ...       ...       ...       ...   
10432 -0.128929 -0.040001  0.057807  0.557894  0.261718 -0.930856 -0.044076   
10433  0.266074  0.556689 -0.020434  0.176624  0.261718 -0.515608  0.597681   
10434 -0.054866  0.580242  0.032912 -0.016668  0.261718  1.519109  0.371178   
10435  0.080916  0.588093  0.015130  0.002250  0.261718 -0.930856 -0.270579   
10436  0.377169  0.014957  0.381439  0.292753  0.261718 -1.470679 -0.006326   

             F8        F9       F10 Class  
0      0.929823  0.251173  0.159345     A  
1      0.636203  0.282354  0.515587     A  
2     -0.888236 -0.123005  0.582939     A  
3      1.051693  0.594169 -0.533994     A  
4      0.051062  0.032902 -0.086652     F  
...         ...       ...       ...   ...  
10432  1.158458  2.277968 -0.699884     X  
10433  0.178349  0.625350 -0.657245     G  
10434 -0.985508 -0.403638  1.276301     A  
10435  0.163807 -0.091823 -0.593329     F  
10436 -0.494919 -0.247731 -1.212974     H  

[20867 rows x 11 columns]

In [4]:
# Lo pasamos a csv
data.to_csv("./avila.csv", index = False)

In [5]:
file = pd.read_csv('avila.csv')
file

F1        F2        F3        F4        F5        F6        F7  \
0      0.266074 -0.165620  0.320980  0.483299  0.172340  0.273364  0.371178   
1      0.130292  0.870736 -3.210528  0.062493  0.261718  1.436060  1.465940   
2     -0.116585  0.069915  0.068476 -0.783147  0.261718  0.439463 -0.081827   
3      0.031541  0.297600 -3.210528 -0.583590 -0.721442 -0.307984  0.710932   
4      0.229043  0.807926 -0.052442  0.082634  0.261718  0.148790  0.635431   
...         ...       ...       ...       ...       ...       ...       ...   
20862 -0.128929 -0.040001  0.057807  0.557894  0.261718 -0.930856 -0.044076   
20863  0.266074  0.556689 -0.020434  0.176624  0.261718 -0.515608  0.597681   
20864 -0.054866  0.580242  0.032912 -0.016668  0.261718  1.519109  0.371178   
20865  0.080916  0.588093  0.015130  0.002250  0.261718 -0.930856 -0.270579   
20866  0.377169  0.014957  0.381439  0.292753  0.261718 -1.470679 -0.006326   

             F8        F9       F10 Class  
0      0.929823  0.251173  0.159345     A  
1      0.636203  0.282354  0.515587     A  
2     -0.888236 -0.123005  0.582939     A  
3      1.051693  0.594169 -0.533994     A  
4      0.051062  0.032902 -0.086652     F  
...         ...       ...       ...   ...  
20862  1.158458  2.277968 -0.699884     X  
20863  0.178349  0.625350 -0.657245     G  
20864 -0.985508 -0.403638  1.276301     A  
20865  0.163807 -0.091823 -0.593329     F  
20866 -0.494919 -0.247731 -1.212974     H  

[20867 rows x 11 columns]

In [6]:
data = np.asarray(file)
X = data[:,:10]
# Normalizar
X = MinMaxScaler().fit_transform(X)

y = data[:,-1]

In [7]:
y

array(['A', 'A', 'A', ..., 'A', 'F', 'H'], dtype=object)

In [8]:
# Array que tiene por columnas las 12 clases y por filas las 20867 instancias.
# Las componentes de cada fila son todas 0, salvo la de la clase a la que pertenece la instancia donde se encuentra un 1
d = LabelBinarizer().fit(np.unique(y)).transform(y)
d = d.astype(float)

In [9]:
d

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### REGRESION LINEAL MULTIPLE - Apartado 2

In [10]:
X_train, X_test, d_train, d_test = train_test_split(X, d, test_size=0.33, 
                                                    random_state=0, stratify=y)

In [11]:
X_train.shape, X_test.shape, d_train.shape, d_test.shape

((13980, 10), (6887, 10), (13980, 12), (6887, 12))

In [12]:
# Array de la precision de cada clasificador
y_predict = float_info.max * np.ones(d_test.shape, dtype=float)
# Creamos un clasificador para cada clase existente y lo entrenamos con la columna correspondiente
for i in range(d_test.shape[1]):
    regresion = LinearRegression().fit(X_train, d_train[:,i])
    y_predict[:,i] = regresion.predict(X_test)
# Tomamos el clasificador predicho con mayor tasa de acierto para asignarle esa clase
y_predict_test = np.argmax(y_predict, axis=1)

In [13]:
print("Tasa de aciertos =", ac(np.argmax(d_test, axis=1), np.argmax(y_predict, axis=1)))

print("\nMatriz de Confusión:\n", confusion_matrix(np.argmax(d_test, axis=1), np.argmax(y_predict, axis=1)))

Tasa de aciertos = 0.4800348482648468

Matriz de Confusión:
 [[2764    0    0    0    6   32    0    0   27    0    0    0]
 [   0    0    0    0    0    0    0    0    3    0    0    0]
 [  55    0    0    0    4    3    0    0    6    0    0    0]
 [ 222    0    0    0    1    1    0    0    9    0    0    0]
 [ 668    0    0    0   18   21    0    0   15    0    1    0]
 [1272    0    0    0    0    7    0    0   16    0    0    0]
 [ 287    0    0    0    1    3    0    0    4    0    0    0]
 [ 283    0    0    0    2   29    0    0   29    0    0    0]
 [  66    0    0    0    4    4    0    0  470    0    5    0]
 [  26    0    0    0    3    0    0    0    0    0    0    0]
 [ 206    0    0    0   12    0    0    0   79    0   47    0]
 [  41    0    0    0    1    1    0    0  133    0    0    0]]


### VALIDACION CRUZADA ESTRATIFICADA (K-FOLD) Apartado 3

In [14]:
# Creación de 10 particiones para realizar validación cruzada
kfold = StratifiedKFold(n_splits=10, random_state=0, shuffle=True)

In [15]:
# Array que almacenará la tasa de acierto de cada partición
aciertos = np.zeros((10), dtype=float)
k = 0
print("ACIERTOS\n")
# Creación, entrenamiento y predicción de los 12 clasificadores en las 10 particiones train-test
for train_index, test_index in kfold.split(X, d[:,0]):
    X_train, X_test = X[train_index], X[test_index]
    d_train, d_test = d[train_index], d[test_index]
    y_test = np.zeros(d_test.shape, dtype=float)
    for i in range(d.shape[1]):
        regresion = LinearRegression().fit(X_train,d_train[:,i])
        y_test[:,i] = regresion.predict(X[test_index])
    # Tomamos el clasificador predicho con mayor tasa de acierto para asignarle esa clase
    # Tasa de acierto de una partición
    aciertos[k] = ac(np.argmax(d_test, axis=1), np.argmax(y_test, axis=1))
    print(aciertos[k])
    k += 1
print("\n\nTasa de aciertos =", np.mean(aciertos))   

ACIERTOS

0.4791566842357451
0.4853857211308098
0.486823191183517
0.48634403449928126
0.47963584091998085
0.48490656444657404
0.4834690943938668
0.47315436241610737
0.48609779482262705
0.4741131351869607


Tasa de aciertos = 0.4819086423235469


### REGRESION LOGISTICA CON HOLD-OUT- Apartado 4

In [16]:
# Separación 2/3 y 1/3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1./3., random_state=0, stratify=y)

# Creación y entrenamiento del clasificador de Regresión Logística
clf = LogisticRegression(random_state=0, multi_class='auto', solver='lbfgs', max_iter=500)
clf.fit(X_train, y_train)

# Tasa de acierto para los datos de prueba y las clases a las que pertenecen
acu = clf.score(X_test, y_test)

print("\033[1mTasa de acierto:\033[0m %.4f" %acu)

Tasa de acierto: 0.4928


In [17]:
# Predicciones del conjunto de test
pred = clf.predict(X_test)

# Matriz de confusión
cm = confusion_matrix(y_test,pred)

print("\033[1mMatriz de confusión:\033[0m\n")
for i in np.unique(y_test):
    if (i == 'A'):
        print("  ",end=" ")
    print(" ",i,"",end=" ")
print("\n")
print(cm)

Matriz de confusión:

     A    B    C    D    E    F    G    H    I    W    X    Y  

[[2813    0    0    0   12   29    0    1    0    0    2    0]
 [   3    0    0    0    0    0    0    0    0    0    0    0]
 [  62    0    0    0    0    7    0    0    0    0    0    0]
 [ 230    0    0    0    1    4    0    0    0    0    0    0]
 [ 711    0    0    0    1   17    0    0    0    0    1    0]
 [1285    0    0    0    7    9    0    3    4    0    0    0]
 [ 295    0    0    0    0    0    0    1    0    0    2    0]
 [ 300    0    0    0    0   42    0    0    4    0    0    0]
 [  56    0    0    0    3    2    0    1  489    0    3    0]
 [  30    0    0    0    0    0    0    0    0    0    0    0]
 [ 226    0    0    0    5    1    0    0    0    0  116    0]
 [ 125    0    0    0    2    0    0    0   19    0   32    0]]


### REGRESIÓN LOGISTICA CON VALIDACIÓN CRUZADA- Apartado 4

In [18]:
# Creación del clasificador de Regresión logística
clf = LogisticRegression(random_state=0, multi_class='auto', solver='lbfgs', max_iter=500)

# El método cross_val_score utiliza la estrategia de estratificación al ser cv un número entero
scores = cross_val_score(clf, X, y, cv=10)

# Tasa de acierto
print("\033[1mTasa de acierto:\033[0m %.4f" %np.mean(scores, dtype=np.float64))

Tasa de acierto: 0.4993
